### PR TITLE
Optimize compilation of snmalloc

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by daanx** [comment]
.. uh, not sure about this PR; we want to compare allocators as fairly as possible (as this is repo is really meant for research in allocator algorithms) and unless we compile all of the allocators native to the machine we should not compile one of them with it. I have not checked though in detail what the other allocators do. I am guessing though that most of the time using `-march=native` is not possible for real programs?

**Comment by jvoisin** [comment]
Good question: there are pros and cons for this one :/

**Comment by daanx** [comment]
Yes, a bit tricky; just noticed the Hoard uses `-flto -O3` while many others use `-O2`; not sure. I generally prefer using standard checkout, build, and run without extra settings if possible.

**Comment by jvoisin** [comment]
And scudo uses custom compilation options as well :/

**Comment by mjp41** [comment]
> Yes, a bit tricky; just noticed the Hoard uses -flto -O3 while many others use -O2; not sure. I generally prefer using standard checkout, build, and run without extra settings if possible.

As do I.  I would personally not enable this feature.  We initially had this enabled by default, but we had complaints from users, and made it opt in, in case anyone was using.  I don't think it makes any difference to performance when I have benchmarked it.

snmalloc effectively has `-flto` as it is header only, so only forms a single compilation unit.

Perhaps, if we are to go down this route, then it would needed to be `-tuned` variants, but I think the discussion on #57 impacts on this.

**Comment by daanx** [comment]
I guess this is fixed now by #73?

**Comment by jvoisin** [comment]
Absolutely

**Pull request closed without merging**
