### PR TITLE
Use Google's tcmalloc instead of an old fork

### LINKED ISSUE #108: Add the new TCMalloc
Unfortunately, there are two allocators both called tcmalloc. You are using the one from the gperftools repo, but a newer fork from upstream which uses restartable sequences is available at https://github.com/google/tcmalloc. It would be nice to be able to see results for both of them along with mimalloc.

### PR DESCRIPTION
**Pull request by jvoisin**
This should fix #108

### CODE REVIEW

**Comment by mjp41** [comment]
@jvoisin do you think we should could both forks of tcmalloc?  I don't think the newer fork supports Mac.

**Comment by jvoisin** [comment]
I'm not a big fan of keeping an outdated fork of tcmalloc, since it's not representative of anything :/

**Comment by daanx** [comment]
Thanks for bringing this in Julien :-). Perhaps we should keep tcmalloc from gperftools and also add the "new" tcmalloc as tcmalloc2 ?   It is not entirely clear to me that the main tcmalloc in gperftools is no longer maintained (?) and it does support macOS and Windows while the new one just seems to run on Linux (? is that right?).

**Comment by jvoisin** [comment]
Alright, let's keep the ~old tcmalloc then :)

**Pull request merged**
