### PR TITLE
Make the CI run on OSX as well

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by mjp41** [comment]
Awesome for doing this. I've dropped my PR in favour of yours.  I think the Yaml is not quite correct for two jobs you probably won't to replace `build-all` with `build-linux` and `build-mac`.

I was having a probably with Hoard building with my PR.  But I don't have a machine to debug on, so was not looking forward to a CI based build debug.

**Comment by daanx** [comment]
@jvoisin : I can build hoard on my macOS M1 -- we need to checkout a recent version though (I have
```
version_hd=5afe855
```

are you sure it does not build?

**Comment by jvoisin** [comment]
This is what the CI is saying:

```
 ~/work/mimalloc-bench/mimalloc-bench/extern ~/work/mimalloc-bench/mimalloc-bench
Cloning into 'Hoard'...
HEAD is now at 5afe855 Merge pull request #62 from devnexen/netbsd_port
git clone https://github.com/emeryberger/Heap-Layers
Cloning into 'Heap-Layers'...
clang++ -ftls-model=initial-exec -ftemplate-depth=1024 -arch x86_64 -arch arm64 -pipe -g -std=c++14 -flto -O3 -DNDEBUG -ffast-math -fno-builtin-malloc -Wall -Wextra -Wshadow -Wconversion -Wuninitialized  -I. -Iinclude -Iinclude/util -Iinclude/hoard -Iinclude/superblocks -IHeap-Layers -D_REENTRANT=1 -compatibility_version 1 -current_version 1 -D'CUSTOM_PREFIX(x)=xx##x' source/libhoard.cpp Heap-Layers/wrappers/macwrapper.cpp source/mactls.cpp -dynamiclib -install_name /usr/local/lib/libhoard.dylib -o libhoard.dylib -ldl -lpthread 
In file included from source/libhoard.cpp:23:
In file included from /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/new:90:
In file included from /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/exception:81:
In file included from /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:85:
In file included from /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:97:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:62:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
#error Unsupported architecture
 ^
 ```

**Comment by mjp41** [comment]
I wondered if it was `-arch arm64` was not supported on the CI machines.

**Comment by jvoisin** [comment]
It was running on 10.15: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

Let's try with 11

**Comment by daanx** [comment]
Are the CI machines running M1's or are they x64 ?   I just tried building on macOS x64 and it indeed did not build; the hoard makefile has `-arch x86_64 -arch arm64` ... that does not seem right?

**Comment by daanx** [comment]
It seems to pass in actions! :-) .. let me know when you think I should merge this PR

**Comment by jvoisin** [comment]
It's good now. Github's naming scheme is confusing: macos-latest isn't the latest…

**Comment by mjp41** [comment]
@jvoisin Thanks for adding Mac Support.

**Pull request merged**
