### PR TITLE
Run the CI every Monday

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by mjp41** [comment]
@jvoisin I think this is a good idea, but I wonder how we will know if it has failed?  If it is a silent failure, then we are just expending compute without the benefit.

**Comment by jvoisin** [comment]
@daanx will get an email, along with all the people "watching" the repository I think.

**Comment by mjp41** [comment]
Although, @daanx has given me permission to merge, I would sooner he decide on this one.

**Comment by daanx** [comment]
I like the idea of running every week (if we get email on failure that is). If this works well we could perhaps set up the build script to have 2 modes: by default use the "latest" versions (like the master branch) but also have a mode with the latest manually specified "known good" versions.

**Comment by daanx** [comment]
If no-one objects, I'll merge this soon.  Thanks Julien!

**Comment by jvoisin** [comment]
> I like the idea of running every week (if we get email on failure that is). If this works well we could perhaps set up the build script to have 2 modes: by default use the "latest" versions (like the master branch) but also have a mode with the latest manually specified "known good" versions.

Sure, it shouldn't be hard to do :)

**Pull request merged**
